using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class AuthorTests : EntityTestBase<Author>
    {
        [TestMethod]
        public void Constructor_ShouldInitializeCollections()
        {
            // Act
            var author = new Author();

            // Assert
            author.Books.Should().NotBeNull();
            author.Books.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var author1 = new Author();
            var author2 = new Author();

            // Assert
            author1.Id.Should().NotBeEmpty();
            author2.Id.Should().NotBeEmpty();
            author1.Id.Should().NotBe(author2.Id);
        }

        [TestMethod]
        public void ValidAuthor_ShouldPassValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .With(a => a.FirstName, "John")
                .With(a => a.LastName, "Doe")
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void FirstName_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .Without(a => a.FirstName)
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("First Name is required"));
        }

        [TestMethod]
        public void FirstName_WhenTooShort_ShouldFailValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .With(a => a.FirstName, "A")
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Fist Name must have between"));
        }

        [TestMethod]
        public void FirstName_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .With(a => a.FirstName, new string('A', 101))
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Fist Name must have between"));
        }

        [TestMethod]
        public void FirstName_WhenContainsNumbers_ShouldFailValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .With(a => a.FirstName, "John123")
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("First Name can only contain letters and spaces"));
        }

        [TestMethod]
        public void FirstName_WhenValid_ShouldPassValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .With(a => a.FirstName, "William")
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().NotContain(vr =>
                vr.MemberNames.Contains("FirstName"));
        }

        [TestMethod]
        public void LastName_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .Without(a => a.LastName)
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Last name is required"));
        }

        [TestMethod]
        public void LastName_WhenContainsNumbers_ShouldFailValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .With(a => a.LastName, "Shakespeare123")
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Last Name can only contain letters and spaces"));
        }

        [TestMethod]
        public void LastName_AtMinimumLength_ShouldPassValidation()
        {
            // Arrange
            var author = _fixture.Build<Author>()
                .With(a => a.FirstName, "Ed")
                .With(a => a.LastName, "Po")
                .Create();

            // Act
            var validationResults = ValidateEntity(author);

            // Assert
            validationResults.Should().NotContain(vr =>
                vr.MemberNames.Contains("LastName"));
        }

        [TestMethod]
        public void Books_ShouldAllowAdding()
        {
            // Arrange
            var author = new Author();
            var book = new Book(10);

            // Act
            author.Books.Add(book);

            // Assert
            author.Books.Should().Contain(book);
        }

        [TestMethod]
        public void Books_ShouldAllowRemoving()
        {
            // Arrange
            var author = new Author();
            var book = new Book(10);
            author.Books.Add(book);

            // Act
            author.Books.Remove(book);

            // Assert
            author.Books.Should().NotContain(book);
        }

        [TestMethod]
        public void Books_CollectionShouldBeProtectedSet()
        {
            // Arrange
            var author = new Author();

            // Act & Assert
            author.Books.GetType().GetProperty("Books")?.SetMethod?.IsFamily
                .Should().BeTrue();
        }

        [TestMethod]
        public void Books_ShouldBeVirtualForLazyLoading()
        {
            // Arrange
            var author = new Author();

            // Act & Assert
            author.Books.GetType().Name.Should().Contain("HashSet");
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var author = new Author
            {
                FirstName = "Test",
                LastName = "Author"
            };

            // Assert
            author.FirstName.Should().Be("Test");
            author.LastName.Should().Be("Author");
        }

        [TestMethod]
        public void Equals_SameId_ShouldBeConsideredEqual()
        {
            // Arrange
            var id = Guid.NewGuid();
            var author1 = new Author { Id = id };
            var author2 = new Author { Id = id };

            // Act & Assert
            author1.Id.Should().Be(author2.Id);
        }
    }
}
