using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class BookCopyTests : EntityTestBase<BookCopy>
    {
        [TestMethod]
        public void Constructor_WithParameter_ShouldInitializeProperties()
        {
            // Act
            var bookCopy = new BookCopy(isLectureRoomOnly: true);

            // Assert
            bookCopy.Id.Should().NotBeEmpty();
            bookCopy.IsLectureRoomOnly.Should().BeTrue();
            bookCopy.IsAvailable.Should().BeTrue();
            bookCopy.Borrowings.Should().NotBeNull();
            bookCopy.Borrowings.Should().BeEmpty();
        }

        [TestMethod]
        public void Constructor_WithFalseParameter_ShouldInitializeAsNotLectureRoomOnly()
        {
            // Act
            var bookCopy = new BookCopy(isLectureRoomOnly: false);

            // Assert
            bookCopy.IsLectureRoomOnly.Should().BeFalse();
        }

        [TestMethod]
        public void Constructor_WithTrueParameter_ShouldInitializeAsLectureRoomOnly()
        {
            // Act
            var bookCopy = new BookCopy(isLectureRoomOnly: true);

            // Assert
            bookCopy.IsLectureRoomOnly.Should().BeTrue();
        }

        [TestMethod]
        public void CreatingInstanceWithActivator_WhenNoPublicParameterlessCtorExists_ShouldThrow()
        {
            // Arrange & Act
            Action act = () => Activator.CreateInstance<BookCopy>();

            // Assert
            act.Should().Throw<MissingMethodException>();
        }

        [TestMethod]
        public void ProtectedConstructor_ShouldCreateInstance_WhenUsingActivatorNonPublic()
        {
            // Arange & Act
            var instance = Activator.CreateInstance(typeof(BookCopy), nonPublic: true) as BookCopy;

            // Assert
            Assert.IsNotNull(instance);
            Assert.IsFalse(instance.IsLectureRoomOnly);
            Assert.IsTrue(instance.IsAvailable);
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var bookCopy1 = new BookCopy(isLectureRoomOnly: false);
            var bookCopy2 = new BookCopy(isLectureRoomOnly: false);

            // Assert
            bookCopy1.Id.Should().NotBeEmpty();
            bookCopy2.Id.Should().NotBeEmpty();
            bookCopy1.Id.Should().NotBe(bookCopy2.Id);
        }

        [TestMethod]
        public void IsAvailable_ShouldBeTrueByDefault()
        {
            // Arrange & Act
            var bookCopy = new BookCopy(isLectureRoomOnly: false);

            // Assert
            bookCopy.IsAvailable.Should().BeTrue();
        }

        [TestMethod]
        public void IsLectureRoomOnly_ShouldBeImmutableAfterConstruction()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: true);
            var property = typeof(BookCopy).GetProperty("IsLectureRoomOnly");

            // Act & Assert
            property.SetMethod.IsPrivate.Should().BeTrue();
            bookCopy.IsLectureRoomOnly.Should().BeTrue();
        }

        [TestMethod]
        public void Edition_ShouldBeRequired()
        {
            // Arrange
            var bookCopy = _fixture.Build<BookCopy>()
                .Without(bc => bc.Edition)
                .Create();

            // Act
            var validationResults = ValidateEntity(bookCopy);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Edition is required"));
        }

        [TestMethod]
        public void IsBorrowable_WhenAvailableAndNotLectureRoomOnly_ShouldReturnTrue()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);

            // Act
            var isBorrowable = bookCopy.IsBorrowable();

            // Assert
            isBorrowable.Should().BeTrue();
        }

        [TestMethod]
        public void IsBorrowable_WhenNotAvailable_ShouldReturnFalse()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);
            bookCopy.MarkAsBorrowed();

            // Act
            var isBorrowable = bookCopy.IsBorrowable();

            // Assert
            isBorrowable.Should().BeFalse();
        }

        [TestMethod]
        public void IsBorrowable_WhenLectureRoomOnly_ShouldReturnFalse()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: true);

            // Act
            var isBorrowable = bookCopy.IsBorrowable();

            // Assert
            isBorrowable.Should().BeFalse();
        }

        [TestMethod]
        public void MarkAsBorrowed_WhenBorrowable_ShouldSetIsAvailableToFalse()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);

            // Act
            bookCopy.MarkAsBorrowed();

            // Assert
            bookCopy.IsAvailable.Should().BeFalse();
        }

        [TestMethod]
        public void MarkAsBorrowed_WhenNotBorrowable_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);
            bookCopy.MarkAsBorrowed();

            // Act & Assert
            bookCopy.Invoking(bc => bc.MarkAsBorrowed())
                .Should().Throw<InvalidOperationException>()
                .WithMessage("Cannot borrow a book copy that is not available or is lecture-room-only.");
        }

        [TestMethod]
        public void MarkAsBorrowed_WhenLectureRoomOnly_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: true);

            // Act & Assert
            bookCopy.Invoking(bc => bc.MarkAsBorrowed())
                .Should().Throw<InvalidOperationException>()
                .WithMessage("Cannot borrow a book copy that is not available or is lecture-room-only.");
        }

        [TestMethod]
        public void MarkAsReturned_ShouldSetIsAvailableToTrue()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);
            bookCopy.MarkAsBorrowed();

            // Act
            bookCopy.MarkAsReturned();

            // Assert
            bookCopy.IsAvailable.Should().BeTrue();
        }

        [TestMethod]
        public void MarkAsReturned_WhenAlreadyAvailable_ShouldRemainTrue()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);

            // Act
            bookCopy.MarkAsReturned();

            // Assert
            bookCopy.IsAvailable.Should().BeTrue();
        }

        [TestMethod]
        public void Borrowings_ShouldAllowAdding()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);
            var borrowing = new Borrowing();

            // Act
            bookCopy.Borrowings.Add(borrowing);

            // Assert
            bookCopy.Borrowings.Should().Contain(borrowing);
        }

        [TestMethod]
        public void Borrowings_ShouldAllowRemoving()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);
            var borrowing = new Borrowing();
            bookCopy.Borrowings.Add(borrowing);

            // Act
            bookCopy.Borrowings.Remove(borrowing);

            // Assert
            bookCopy.Borrowings.Should().NotContain(borrowing);
        }

        [TestMethod]
        public void Borrowings_ShouldBeVirtualForLazyLoading()
        {
            // Arrange
            var bookCopy = new BookCopy(isLectureRoomOnly: false);

            // Act & Assert
            bookCopy.Borrowings.GetType().Name.Should().Contain("HashSet");
        }

        [TestMethod]
        public void IsAvailable_SetterShouldBePrivate()
        {
            // Arrange
            var property = typeof(BookCopy).GetProperty("IsAvailable");

            // Act & Assert
            property.SetMethod.IsPrivate.Should().BeTrue();
        }

        [TestMethod]
        public void Edition_SetterShouldBePublicForEntityFramework()
        {
            // Arrange & Act
            var bookCopy = new BookCopy(isLectureRoomOnly: false)
            {
                Edition = new Edition()
            };

            // Assert
            bookCopy.Edition.Should().NotBeNull();
        }
    }
}
