using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class BookTests : EntityTestBase<Book>
    {
        [TestMethod]
        public void Constructor_WithInitialCopies_ShouldSetInitialCopies()
        {
            // Arrange & Act
            var book = new Book(initialCopies: 10);

            // Assert
            book.InitialCopies.Should().Be(10);
        }

        [TestMethod]
        public void Constructor_WithZeroInitialCopies_ShouldThrowArgumentOutOfRangeException()
        {
            // Arrange & Act & Assert
            Action act = () => new Book(initialCopies: 0);
            act.Should().Throw<ArgumentOutOfRangeException>();
        }

        [TestMethod]
        public void Constructor_WithNegativeInitialCopies_ShouldThrowArgumentOutOfRangeException()
        {
            // Arrange & Act & Assert
            Action act = () => new Book(initialCopies: -5);
            act.Should().Throw<ArgumentOutOfRangeException>();
        }

        [TestMethod]
        public void ProtectedConstructor_ShouldInitializeCollections()
        {
            // Arrange & Act
            var book = Activator.CreateInstance(typeof(Book), nonPublic: true) as Book;

            // Assert
            book.Authors.Should().NotBeNull();
            book.Authors.Should().BeEmpty();
            book.Domains.Should().NotBeNull();
            book.Domains.Should().BeEmpty();
            book.Editions.Should().NotBeNull();
            book.Editions.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var book1 = new Book(initialCopies: 10);
            var book2 = new Book(initialCopies: 10);

            // Assert
            book1.Id.Should().NotBeEmpty();
            book2.Id.Should().NotBeEmpty();
            book1.Id.Should().NotBe(book2.Id);
        }

        [TestMethod]
        public void ValidBook_ShouldPassValidation()
        {
            // Arrange
            var book = _fixture.Build<Book>()
                .FromFactory(() => new Book(initialCopies: 10))
                .With(b => b.Title, "Test Book Title")
                .With(b => b.Description, "Test Description")
                .Create();

            // Act
            var validationResults = ValidateEntity(book);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void Title_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var book = _fixture.Build<Book>()
                .FromFactory(() => new Book(initialCopies: 10))
                .Without(b => b.Title)
                .Create();

            // Act
            var validationResults = ValidateEntity(book);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Title is required"));
        }

        [TestMethod]
        public void Title_WhenTooShort_ShouldFailValidation()
        {
            // Arrange
            var book = _fixture.Build<Book>()
                .FromFactory(() => new Book(initialCopies: 10))
                .With(b => b.Title, "A")
                .Create();

            // Act
            var validationResults = ValidateEntity(book);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Title must be between"));
        }

        [TestMethod]
        public void Title_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var book = _fixture.Build<Book>()
                .FromFactory(() => new Book(initialCopies: 10))
                .With(b => b.Title, new string('A', 301))
                .Create();

            // Act
            var validationResults = ValidateEntity(book);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Title must be between"));
        }

        [TestMethod]
        public void Description_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var book = _fixture.Build<Book>()
                .FromFactory(() => new Book(initialCopies: 10))
                .With(b => b.Description, new string('A', 501))
                .Create();

            // Act
            var validationResults = ValidateEntity(book);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Description cannot exceed"));
        }

        [TestMethod]
        public void IsAvailableForBorrowing_WhenNoInitialCopies_ShouldReturnFalse()
        {
            // Arrange
            var book = Activator.CreateInstance(typeof(Book), nonPublic: true) as Book;

            // Act
            var result = book.IsAvailableForBorrowing();

            // Assert
            result.Should().BeFalse();
        }

        [TestMethod]
        public void IsAvailableForBorrowing_WhenBelowThreshold_ShouldReturnFalse()
        {
            // Arrange
            var book = new Book(initialCopies: 100);
            var edition = new Edition();
            for (int i = 0; i < 9; i++)
            {
                edition.BookCopies.Add(new BookCopy(isLectureRoomOnly: false));
            }
            book.Editions.Add(edition);

            // Act
            var result = book.IsAvailableForBorrowing();

            // Assert
            result.Should().BeFalse();
        }

        [TestMethod]
        public void IsAvailableForBorrowing_WhenAtThreshold_ShouldReturnTrue()
        {
            // Arrange
            var book = new Book(initialCopies: 100);
            var edition = new Edition();
            for (int i = 0; i < 10; i++)
            {
                edition.BookCopies.Add(new BookCopy(isLectureRoomOnly: false));
            }
            book.Editions.Add(edition);

            // Act
            var result = book.IsAvailableForBorrowing();

            // Assert
            result.Should().BeTrue();
        }

        [TestMethod]
        public void IsAvailableForBorrowing_WhenOnlyLectureRoomCopies_ShouldReturnFalse()
        {
            // Arrange
            var book = new Book(initialCopies: 10);
            var edition = new Edition();
            edition.BookCopies.Add(new BookCopy(isLectureRoomOnly: true));
            book.Editions.Add(edition);

            // Act
            var result = book.IsAvailableForBorrowing();

            // Assert
            result.Should().BeFalse();
        }

        [TestMethod]
        public void Authors_ShouldAllowAdding()
        {
            // Arrange
            var book = new Book(initialCopies: 10);
            var author = new Author();

            // Act
            book.Authors.Add(author);

            // Assert
            book.Authors.Should().Contain(author);
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var book = new Book(initialCopies: 10)
            {
                Title = "Test Book",
                Description = "Test Description"
            };

            // Assert
            book.Title.Should().Be("Test Book");
            book.Description.Should().Be("Test Description");
        }
    }
}
