using AutoFixture;
using AutoFixture.AutoMoq;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class BookTypeTests : EntityTestBase<BookType>
    {
        [TestMethod]
        public void Constructor_ShouldInitializeCollections()
        {
            // Act
            var bookType = new BookType();

            // Assert
            bookType.Editions.Should().NotBeNull();
            bookType.Editions.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var bookType1 = new BookType();
            var bookType2 = new BookType();

            // Assert
            bookType1.Id.Should().NotBeEmpty();
            bookType2.Id.Should().NotBeEmpty();
            bookType1.Id.Should().NotBe(bookType2.Id);
        }

        [TestMethod]
        public void ValidBookType_ShouldPassValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .With(bt => bt.Name, "Hardcover")
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void Name_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .Without(bt => bt.Name)
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().Contain(vr => vr.ErrorMessage.Contains("Book type name is required"));
        }

        [TestMethod]
        public void Name_WhenTooShort_ShouldFailValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .With(bt => bt.Name, "A")
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Book type name must be between"));
        }

        [TestMethod]
        public void Name_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .With(bt => bt.Name, new string('A', 51))
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Book type name must be between"));
        }

        [TestMethod]
        public void Name_WhenContainsNumbers_ShouldFailValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .With(bt => bt.Name, "Hardcover 2")
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Book type name can only contain letters and spaces"));
        }

        [TestMethod]
        public void Name_WhenValid_ShouldPassValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .With(bt => bt.Name, "Paperback")
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().NotContain(vr =>
                vr.MemberNames.Contains("Name"));
        }

        [TestMethod]
        public void Name_AtMinimumLength_ShouldPassValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .With(bt => bt.Name, "AB")
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().NotContain(vr =>
                vr.MemberNames.Contains("Name"));
        }

        [TestMethod]
        public void Name_AtMaximumLength_ShouldPassValidation()
        {
            // Arrange
            var bookType = _fixture.Build<BookType>()
                .With(bt => bt.Name, new string('A', 50))
                .Create();

            // Act
            var validationResults = ValidateEntity(bookType);

            // Assert
            validationResults.Should().NotContain(vr =>
                vr.MemberNames.Contains("Name"));
        }

        [TestMethod]
        public void Editions_ShouldAllowAdding()
        {
            // Arrange
            var bookType = new BookType();
            var edition = new Edition();

            // Act
            bookType.Editions.Add(edition);

            // Assert
            bookType.Editions.Should().Contain(edition);
        }

        [TestMethod]
        public void Editions_ShouldAllowRemoving()
        {
            // Arrange
            var bookType = new BookType();
            var edition = new Edition();
            bookType.Editions.Add(edition);

            // Act
            bookType.Editions.Remove(edition);

            // Assert
            bookType.Editions.Should().NotContain(edition);
        }

        [TestMethod]
        public void Editions_ShouldBeVirtualForLazyLoading()
        {
            // Arrange
            var bookType = new BookType();

            // Act & Assert
            bookType.Editions.GetType().Name.Should().Contain("HashSet");
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var bookType = new BookType
            {
                Name = "Test Book Type"
            };

            // Assert
            bookType.Name.Should().Be("Test Book Type");
        }

        [TestMethod]
        public void Equals_SameId_ShouldBeConsideredEqual()
        {
            // Arrange
            var id = Guid.NewGuid();
            var bookType1 = new BookType { Id = id };
            var bookType2 = new BookType { Id = id };

            // Act & Assert
            bookType1.Id.Should().Be(bookType2.Id);
        }

        [TestMethod]
        public void Equals_DifferentId_ShouldNotBeConsideredEqual()
        {
            // Arrange
            var bookType1 = new BookType();
            var bookType2 = new BookType();

            // Act & Assert
            bookType1.Id.Should().NotBe(bookType2.Id);
        }

        [TestMethod]
        public void Collections_ShouldBeInitialized()
        {
            // Arrange & Act
            var bookType = new BookType();

            // Assert
            bookType.Editions.Should().NotBeNull();
        }
    }
}
