using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class BorrowingTests : EntityTestBase<Borrowing>
    {
        [TestMethod]
        public void Constructor_ShouldInitializeCollections()
        {
            // Act
            var borrowing = new Borrowing();

            // Assert
            borrowing.BookCopies.Should().NotBeNull();
            borrowing.BookCopies.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var borrowing1 = new Borrowing();
            var borrowing2 = new Borrowing();

            // Assert
            borrowing1.Id.Should().NotBeEmpty();
            borrowing2.Id.Should().NotBeEmpty();
            borrowing1.Id.Should().NotBe(borrowing2.Id);
        }

        [TestMethod]
        public void ValidBorrowing_ShouldPassValidation()
        {
            // Arrange
            var borrowing = _fixture.Build<Borrowing>()
                .With(b => b.BorrowDate, DateTime.Now.AddDays(-10))
                .With(b => b.DueDate, DateTime.Now.AddDays(20))
                .Without(b => b.ReturnDate)
                .Without(b => b.ExtensionDays)
                .Create();

            // Act
            var validationResults = ValidateEntity(borrowing);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void Reader_ShouldBeRequired()
        {
            // Arrange
            var borrowing = _fixture.Build<Borrowing>()
                .Without(b => b.Reader)
                .Create();

            // Act
            var validationResults = ValidateEntity(borrowing);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Reader is required"));
        }

        [TestMethod]
        public void Librarian_ShouldBeRequired()
        {
            // Arrange
            var borrowing = _fixture.Build<Borrowing>()
                .Without(b => b.Librarian)
                .Create();

            // Act
            var validationResults = ValidateEntity(borrowing);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Librarian is required"));
        }

        [TestMethod]
        public void Finish_WhenNotFinished_ShouldSetReturnDate()
        {
            // Arrange
            var borrowing = _fixture.Build<Borrowing>()
                .Without(b => b.ReturnDate)
                .Create();
            var expectedReturnDate = DateTime.Now;

            // Act
            borrowing.Finish(expectedReturnDate);

            // Assert
            borrowing.ReturnDate.Should().Be(expectedReturnDate);
        }

        [TestMethod]
        public void Finish_WhenAlreadyFinished_ShouldThrowInvalidOperationException()
        {
            // Arrange
            var borrowing = _fixture.Build<Borrowing>()
                .With(b => b.ReturnDate, DateTime.Now.AddDays(-1))
                .Create();

            // Act & Assert
            borrowing.Invoking(b => b.Finish())
                .Should().Throw<InvalidOperationException>()
                .WithMessage("This borrowing has already been finished.");
        }

        [TestMethod]
        public void Finish_ShouldMarkBookCopiesAsReturned()
        {
            // Arrange
            var borrowing = new Borrowing();
            var bookCopy1 = new BookCopy(isLectureRoomOnly: false);
            var bookCopy2 = new BookCopy(isLectureRoomOnly: false);
            bookCopy1.MarkAsBorrowed();
            bookCopy2.MarkAsBorrowed();

            borrowing.BookCopies.Add(bookCopy1);
            borrowing.BookCopies.Add(bookCopy2);

            // Act
            borrowing.Finish();

            // Assert
            bookCopy1.IsAvailable.Should().BeTrue();
            bookCopy2.IsAvailable.Should().BeTrue();
        }

        [TestMethod]
        public void BookCopies_ShouldAllowAdding()
        {
            // Arrange
            var borrowing = new Borrowing();
            var bookCopy = new BookCopy(isLectureRoomOnly: false);

            // Act
            borrowing.BookCopies.Add(bookCopy);

            // Assert
            borrowing.BookCopies.Should().Contain(bookCopy);
        }

        [TestMethod]
        public void BookCopies_ShouldAllowRemoving()
        {
            // Arrange
            var borrowing = new Borrowing();
            var bookCopy = new BookCopy(isLectureRoomOnly: false);
            borrowing.BookCopies.Add(bookCopy);

            // Act
            borrowing.BookCopies.Remove(bookCopy);

            // Assert
            borrowing.BookCopies.Should().NotContain(bookCopy);
        }

        [TestMethod]
        public void BookCopies_ShouldBeVirtualForLazyLoading()
        {
            // Arrange
            var borrowing = new Borrowing();

            // Act & Assert
            borrowing.BookCopies.GetType().Name.Should().Contain("HashSet");
        }

        [TestMethod]
        public void BookCopies_CollectionShouldBeProtectedSet()
        {
            // Arrange
            var borrowing = new Borrowing();

            // Act & Assert
            borrowing.BookCopies.GetType().GetProperty("BookCopies")?.SetMethod?.IsFamily
                .Should().BeFalse();
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var borrowing = new Borrowing
            {
                BorrowDate = DateTime.Now.AddDays(-10),
                DueDate = DateTime.Now.AddDays(20),
                ExtensionDays = 5
            };

            // Assert
            borrowing.BorrowDate.Should().BeBefore(DateTime.Now);
            borrowing.DueDate.Should().BeAfter(DateTime.Now);
            borrowing.ExtensionDays.Should().Be(5);
        }
    }
}
