using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class ConfigurationSettingTests : EntityTestBase<ConfigurationSetting>
    {
        [TestMethod]
        public void Constructor_ShouldSetDefaultValues()
        {
            // Act
            var setting = new ConfigurationSetting();

            // Assert
            setting.Id.Should().NotBeEmpty();
            setting.LastModified.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var setting1 = new ConfigurationSetting();
            var setting2 = new ConfigurationSetting();

            // Assert
            setting1.Id.Should().NotBeEmpty();
            setting2.Id.Should().NotBeEmpty();
            setting1.Id.Should().NotBe(setting2.Id);
        }

        [TestMethod]
        public void ValidConfigurationSetting_ShouldPassValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .With(cs => cs.Key, "TestKey")
                .With(cs => cs.Value, "TestValue")
                .With(cs => cs.DataType, "string")
                .With(cs => cs.Category, "TestCategory")
                .With(cs => cs.Description, "Test Description")
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void Key_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .Without(cs => cs.Key)
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.MemberNames.Contains("Key"));
        }

        [TestMethod]
        public void Key_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .With(cs => cs.Key, new string('A', 101))
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("maximum length"));
        }

        [TestMethod]
        public void Value_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .Without(cs => cs.Value)
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.MemberNames.Contains("Value"));
        }

        [TestMethod]
        public void DataType_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .Without(cs => cs.DataType)
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.MemberNames.Contains("DataType"));
        }

        [TestMethod]
        public void DataType_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .With(cs => cs.DataType, new string('A', 51))
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("maximum length"));
        }

        [TestMethod]
        public void Category_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .With(cs => cs.Category, new string('A', 101))
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("maximum length"));
        }

        [TestMethod]
        public void Description_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var setting = _fixture.Build<ConfigurationSetting>()
                .With(cs => cs.Description, new string('A', 501))
                .Create();

            // Act
            var validationResults = ValidateEntity(setting);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("maximum length"));
        }

        [TestMethod]
        public void LastModified_ShouldBeUtcByDefault()
        {
            // Arrange & Act
            var setting = new ConfigurationSetting();

            // Assert
            setting.LastModified.Kind.Should().Be(DateTimeKind.Utc);
        }

        [TestMethod]
        public void LastModified_CanBeSet()
        {
            // Arrange
            var setting = new ConfigurationSetting();
            var utcTime = DateTime.UtcNow.AddDays(-1);

            // Act
            setting.LastModified = utcTime;

            // Assert
            setting.LastModified.Should().Be(utcTime);
            setting.LastModified.Kind.Should().Be(DateTimeKind.Utc);
        }

        [TestMethod]
        public void Key_ShouldHaveUniqueIndex()
        {
            // Note: This is tested by the [Index(IsUnique = true)] attribute
            // We can verify the attribute exists
            var property = typeof(ConfigurationSetting).GetProperty("Key");
            var attributes = property.GetCustomAttributes(inherit: false);

            // Act & Assert
            attributes.Should().ContainSingle(a => a.GetType().Name.Contains("IndexAttribute"));
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var setting = new ConfigurationSetting
            {
                Key = "TestKey",
                Value = "TestValue",
                DataType = "int",
                Category = "Test",
                Description = "Test Description",
                LastModified = DateTime.UtcNow
            };

            // Assert
            setting.Key.Should().Be("TestKey");
            setting.Value.Should().Be("TestValue");
            setting.DataType.Should().Be("int");
            setting.Category.Should().Be("Test");
            setting.Description.Should().Be("Test Description");
            setting.LastModified.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
        }

        [TestMethod]
        public void DefaultConstructor_ShouldSetLastModifiedToUtcNow()
        {
            // Arrange & Act
            var setting = new ConfigurationSetting();
            var timeBeforeCreation = DateTime.UtcNow.AddSeconds(-1);

            // Assert
            setting.LastModified.Should().BeAfter(timeBeforeCreation);
            setting.LastModified.Should().BeBefore(DateTime.UtcNow.AddSeconds(1));
        }

        [TestMethod]
        public void DataType_CommonValues_ShouldBeValid()
        {
            var commonDataTypes = new[] { "string", "int", "double", "timespan", "bool", "datetime" };

            foreach (var dataType in commonDataTypes)
            {
                // Arrange
                var setting = _fixture.Build<ConfigurationSetting>()
                    .With(cs => cs.DataType, dataType)
                    .Create();

                // Act
                var validationResults = ValidateEntity(setting);

                // Assert
                validationResults.Should().NotContain(vr => vr.MemberNames.Contains("DataType"));
            }
        }

        [TestMethod]
        public void Update_ShouldUpdateLastModified()
        {
            // Arrange
            var setting = new ConfigurationSetting();
            var originalLastModified = setting.LastModified;

            // Act
            setting.Value = "UpdatedValue";
            setting.LastModified = DateTime.UtcNow.AddMinutes(1);

            // Assert
            setting.LastModified.Should().BeAfter(originalLastModified);
        }

        [TestMethod]
        public void Equality_ShouldBeBasedOnId()
        {
            // Arrange
            var id = Guid.NewGuid();
            var setting1 = new ConfigurationSetting { Id = id };
            var setting2 = new ConfigurationSetting { Id = id };

            // Act & Assert
            setting1.Id.Should().Be(setting2.Id);
        }

        [TestMethod]
        public void Category_CanBeNull()
        {
            // Arrange
            var setting = new ConfigurationSetting();

            // Act
            setting.Category = null;

            // Assert
            setting.Category.Should().BeNull();
        }

        [TestMethod]
        public void Description_CanBeNull()
        {
            // Arrange
            var setting = new ConfigurationSetting();

            // Act
            setting.Description = null;

            // Assert
            setting.Description.Should().BeNull();
        }
    }
}
