using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class DomainTests : EntityTestBase<Domain>
    {
        [TestMethod]
        public void Constructor_ShouldInitializeCollections()
        {
            // Act
            var domain = new Domain();

            // Assert
            domain.Subdomains.Should().NotBeNull();
            domain.Subdomains.Should().BeEmpty();
            domain.Books.Should().NotBeNull();
            domain.Books.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var domain1 = new Domain();
            var domain2 = new Domain();

            // Assert
            domain1.Id.Should().NotBeEmpty();
            domain2.Id.Should().NotBeEmpty();
            domain1.Id.Should().NotBe(domain2.Id);
        }

        [TestMethod]
        public void ValidDomain_ShouldPassValidation()
        {
            // Arrange
            var domain = _fixture.Build<Domain>()
                .With(d => d.Name, "Science Fiction")
                .With(d => d.Description, "Fiction based on imagined future scientific or technological advances")
                .Create();

            // Act
            var validationResults = ValidateEntity(domain);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void Name_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var domain = _fixture.Build<Domain>()
                .Without(d => d.Name)
                .Create();

            // Act
            var validationResults = ValidateEntity(domain);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Domain name is required"));
        }

        [TestMethod]
        public void Name_WhenTooShort_ShouldFailValidation()
        {
            // Arrange
            var domain = _fixture.Build<Domain>()
                .With(d => d.Name, "A")
                .Create();

            // Act
            var validationResults = ValidateEntity(domain);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Domain name must be between"));
        }

        [TestMethod]
        public void Name_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var domain = _fixture.Build<Domain>()
                .With(d => d.Name, new string('A', 201))
                .Create();

            // Act
            var validationResults = ValidateEntity(domain);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Domain name must be between"));
        }

        [TestMethod]
        public void Description_WhenTooLong_ShouldFailValidation()
        {
            // Arrange
            var domain = _fixture.Build<Domain>()
                .With(d => d.Description, new string('A', 1001))
                .Create();

            // Act
            var validationResults = ValidateEntity(domain);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Description cannot exceed"));
        }

        [TestMethod]
        public void IsDescendant_WhenOtherDomainIsDirectChild_ShouldReturnTrue()
        {
            // Arrange
            var parent = new Domain { Id = Guid.NewGuid(), Name = "Parent" };
            var child = new Domain { Id = Guid.NewGuid(), Name = "Child" };

            parent.Subdomains.Add(child);

            // Act
            var result = parent.IsDescendant(child);

            // Assert
            result.Should().BeTrue();
        }

        [TestMethod]
        public void IsDescendant_WhenMatchIsOnLaterSibling_ShouldReturnTrue()
        {
            // Arrange
            var parent = new Domain { Id = Guid.NewGuid(), Name = "Parent" };
            var child1 = new Domain { Id = Guid.NewGuid(), Name = "Child1" };
            var child2 = new Domain { Id = Guid.NewGuid(), Name = "Child2" };

            parent.Subdomains.Add(child1);
            parent.Subdomains.Add(child2);

            // Act
            var result = parent.IsDescendant(child2);

            // Assert
            result.Should().BeTrue();
        }

        [TestMethod]
        public void IsDescendant_WhenOtherDomainIsIndirectDescendant_ShouldReturnTrue()
        {
            // Arrange
            var parentDomain = new Domain { Id = Guid.NewGuid(), Name = "Parent" };
            var childDomain = new Domain { Id = Guid.NewGuid(), Name = "Child" };
            var grandChildDomain = new Domain { Id = Guid.NewGuid(), Name = "GrandChild" };

            parentDomain.Subdomains.Add(childDomain);
            childDomain.Subdomains.Add(grandChildDomain);

            // Act
            var result = parentDomain.IsDescendant(grandChildDomain);

            // Assert
            result.Should().BeTrue();
        }

        [TestMethod]
        public void IsDescendant_WhenOtherDomainIsNotDescendant_ShouldReturnFalse()
        {
            // Arrange
            var domain1 = new Domain { Id = Guid.NewGuid(), Name = "Domain1" };
            var domain2 = new Domain { Id = Guid.NewGuid(), Name = "Domain2" };

            // Act
            var result = domain1.IsDescendant(domain2);

            // Assert
            result.Should().BeFalse();
        }

        [TestMethod]
        public void IsDescendant_WhenOtherDomainIsNull_ShouldThrowArgumentNullException()
        {
            // Arrange
            var domain = new Domain();

            // Act & Assert
            domain.Invoking(d => d.IsDescendant(null))
                .Should().Throw<ArgumentNullException>();
        }

        [TestMethod]
        public void IsAncestor_WhenOtherDomainIsAncestor_ShouldReturnTrue()
        {
            // Arrange
            var grandParentDomain = new Domain { Id = Guid.NewGuid(), Name = "GrandParent" };
            var parentDomain = new Domain { Id = Guid.NewGuid(), Name = "Parent", ParentDomain = grandParentDomain };
            var childDomain = new Domain { Id = Guid.NewGuid(), Name = "Child", ParentDomain = parentDomain };

            // Act
            var result = childDomain.IsAncestor(grandParentDomain);

            // Assert
            result.Should().BeTrue();
        }

        [TestMethod]
        public void IsAncestor_WhenOtherDomainIsNotAncestor_ShouldReturnFalse()
        {
            // Arrange
            var domain1 = new Domain { Id = Guid.NewGuid(), Name = "Domain1" };
            var domain2 = new Domain { Id = Guid.NewGuid(), Name = "Domain2" };

            // Act
            var result = domain1.IsAncestor(domain2);

            // Assert
            result.Should().BeFalse();
        }

        [TestMethod]
        public void IsAncestor_WhenOtherDomainIsNull_ShouldThrowArgumentNullException()
        {
            // Arrange
            var domain = new Domain();

            // Act & Assert
            domain.Invoking(d => d.IsAncestor(null))
                .Should().Throw<ArgumentNullException>();
        }

        [TestMethod]
        public void Subdomains_ShouldAllowAdding()
        {
            // Arrange
            var parentDomain = new Domain();
            var subdomain = new Domain();

            // Act
            parentDomain.Subdomains.Add(subdomain);

            // Assert
            parentDomain.Subdomains.Should().Contain(subdomain);
            subdomain.ParentDomain.Should().BeNull();
        }

        [TestMethod]
        public void Books_ShouldAllowAdding()
        {
            // Arrange
            var domain = new Domain();
            var book = new Book(10);

            // Act
            domain.Books.Add(book);

            // Assert
            domain.Books.Should().Contain(book);
        }

        [TestMethod]
        public void ParentDomain_CanBeSetToNullForRootDomain()
        {
            // Arrange
            var domain = new Domain();

            // Act
            domain.ParentDomain = null;

            // Assert
            domain.ParentDomain.Should().BeNull();
        }

        [TestMethod]
        public void Subdomains_CollectionShouldBeProtectedSet()
        {
            // Arrange
            var domain = new Domain();

            // Act & Assert
            domain.Subdomains.GetType().GetProperty("Subdomains")?.SetMethod?.IsFamily
                .Should().BeTrue();
        }

        [TestMethod]
        public void Books_CollectionShouldBeProtectedSet()
        {
            // Arrange
            var domain = new Domain();

            // Act & Assert
            domain.Books.GetType().GetProperty("Books")?.SetMethod?.IsFamily
                .Should().BeTrue();
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var domain = new Domain
            {
                Name = "Test Domain",
                Description = "Test Description"
            };

            // Assert
            domain.Name.Should().Be("Test Domain");
            domain.Description.Should().Be("Test Description");
        }
    }
}
