using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [TestClass]
    public class EditionTests : EntityTestBase<Edition>
    {
        [TestMethod]
        public void Constructor_ShouldInitializeCollections()
        {
            // Act
            var edition = new Edition();

            // Assert
            edition.BookCopies.Should().NotBeNull();
            edition.BookCopies.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var edition1 = new Edition();
            var edition2 = new Edition();

            // Assert
            edition1.Id.Should().NotBeEmpty();
            edition2.Id.Should().NotBeEmpty();
            edition1.Id.Should().NotBe(edition2.Id);
        }

        [TestMethod]
        public void ValidEdition_ShouldPassValidation()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .With(e => e.NumberOfPages, 300)
                .With(e => e.PublicationDate, DateTime.Now.AddDays(-100))
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void NumberOfPages_WhenBelowMinimum_ShouldFailValidation()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .With(e => e.NumberOfPages, 29)
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Number of pages must be at least"));
        }

        [TestMethod]
        public void NumberOfPages_WhenAboveMaximum_ShouldFailValidation()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .With(e => e.NumberOfPages, 5001)
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Number of pages must be at least"));
        }

        [TestMethod]
        public void NumberOfPages_AtMinimum_ShouldPassValidation()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .With(e => e.NumberOfPages, 30)
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);

            // Assert
            validationResults.Should().NotContain(vr =>
                vr.MemberNames.Contains("NumberOfPages"));
        }

        [TestMethod]
        public void NumberOfPages_AtMaximum_ShouldPassValidation()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .With(e => e.NumberOfPages, 5000)
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);

            // Assert
            validationResults.Should().NotContain(vr =>
                vr.MemberNames.Contains("NumberOfPages"));
        }

        [TestMethod]
        public void PublicationDate_WhenInFuture_ShouldBeCaughtByValidator()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .With(e => e.PublicationDate, DateTime.Now.AddDays(1))
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);
            
            // Assert
            edition.PublicationDate.Should().BeAfter(DateTime.Now);
        }

        [TestMethod]
        public void Book_ShouldBeRequired()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .Without(e => e.Book)
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Book is required"));
        }

        [TestMethod]
        public void BookType_ShouldBeRequired()
        {
            // Arrange
            var edition = _fixture.Build<Edition>()
                .Without(e => e.BookType)
                .Create();

            // Act
            var validationResults = ValidateEntity(edition);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Book type is required"));
        }

        [TestMethod]
        public void BookCopies_ShouldAllowRemoving()
        {
            // Arrange
            var edition = new Edition();
            var bookCopy = new BookCopy(isLectureRoomOnly: false);
            edition.BookCopies.Add(bookCopy);

            // Act
            edition.BookCopies.Remove(bookCopy);

            // Assert
            edition.BookCopies.Should().NotContain(bookCopy);
        }

        [TestMethod]
        public void BookCopies_ShouldBeVirtualForLazyLoading()
        {
            // Arrange
            var edition = new Edition();

            // Act & Assert
            edition.BookCopies.GetType().Name.Should().Contain("HashSet");
        }

        [TestMethod]
        public void BookCopies_CollectionShouldBeProtectedSet()
        {
            // Arrange
            var edition = new Edition();

            // Act & Assert
            edition.BookCopies.GetType().GetProperty("BookCopies")?.SetMethod?.IsFamily
                .Should().BeTrue();
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var edition = new Edition
            {
                NumberOfPages = 400,
                PublicationDate = DateTime.Now.AddDays(-365)
            };

            // Assert
            edition.NumberOfPages.Should().Be(400);
            edition.PublicationDate.Should().BeBefore(DateTime.Now);
        }

        [TestMethod]
        public void Book_SetterShouldBePublicForEntityFramework()
        {
            // Arrange & Act
            var edition = new Edition
            {
                Book = new Book(initialCopies: 10)
            };

            // Assert
            edition.Book.Should().NotBeNull();
        }

        [TestMethod]
        public void BookType_SetterShouldBePublicForEntityFramework()
        {
            // Arrange & Act
            var edition = new Edition
            {
                BookType = new BookType()
            };

            // Assert
            edition.BookType.Should().NotBeNull();
        }
    }
}
