using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [TestClass]
    public class LibrarianTests : EntityTestBase<Librarian>
    {
        [TestMethod]
        public void Constructor_ShouldInitializeCollections()
        {
            // Act
            var librarian = new Librarian();

            // Assert
            librarian.ProcessedLoans.Should().NotBeNull();
            librarian.ProcessedLoans.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var librarian1 = new Librarian();
            var librarian2 = new Librarian();

            // Assert
            librarian1.Id.Should().NotBeEmpty();
            librarian2.Id.Should().NotBeEmpty();
            librarian1.Id.Should().NotBe(librarian2.Id);
        }

        [TestMethod]
        public void ValidLibrarian_ShouldPassValidation()
        {
            // Arrange
            var librarian = _fixture.Create<Librarian>();

            // Act
            var validationResults = ValidateEntity(librarian);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void ReaderDetails_CanBeSet()
        {
            // Arrange
            var librarian = new Librarian();
            var reader = new Reader();

            // Act
            librarian.ReaderDetails = reader;

            // Assert
            librarian.ReaderDetails.Should().Be(reader);
        }

        [TestMethod]
        public void ReaderDetails_CanBeNull()
        {
            // Arrange & Act
            var librarian = new Librarian
            {
                ReaderDetails = null
            };

            // Assert
            librarian.ReaderDetails.Should().BeNull();
        }

        [TestMethod]
        public void IsAlsoReader_WhenReaderDetailsNotNull_ShouldReturnTrue()
        {
            // Arrange
            var librarian = new Librarian
            {
                ReaderDetails = new Reader()
            };

            // Act
            var result = librarian.IsAlsoReader();

            // Assert
            result.Should().BeTrue();
        }

        [TestMethod]
        public void IsAlsoReader_WhenReaderDetailsNull_ShouldReturnFalse()
        {
            // Arrange
            var librarian = new Librarian();

            // Act
            var result = librarian.IsAlsoReader();

            // Assert
            result.Should().BeFalse();
        }

        [TestMethod]
        public void ProcessedLoans_ShouldAllowAdding()
        {
            // Arrange
            var librarian = new Librarian();
            var borrowing = new Borrowing();

            // Act
            librarian.ProcessedLoans.Add(borrowing);

            // Assert
            librarian.ProcessedLoans.Should().Contain(borrowing);
        }

        [TestMethod]
        public void ProcessedLoans_ShouldAllowRemoving()
        {
            // Arrange
            var librarian = new Librarian();
            var borrowing = new Borrowing();
            librarian.ProcessedLoans.Add(borrowing);

            // Act
            librarian.ProcessedLoans.Remove(borrowing);

            // Assert
            librarian.ProcessedLoans.Should().NotContain(borrowing);
        }

        [TestMethod]
        public void ProcessedLoans_ShouldBeVirtualForLazyLoading()
        {
            // Arrange
            var librarian = new Librarian();

            // Act & Assert
            librarian.ProcessedLoans.GetType().Name.Should().Contain("HashSet");
        }

        [TestMethod]
        public void ProcessedLoans_CollectionShouldBeProtectedSet()
        {
            // Arrange
            var librarian = new Librarian();

            // Act & Assert
            librarian.ProcessedLoans.GetType().GetProperty("ProcessedLoans")?.SetMethod?.IsFamily
                .Should().BeTrue();
        }

        [TestMethod]
        public void ReaderDetails_SetterShouldBePublicForEntityFramework()
        {
            // Arrange & Act
            var librarian = new Librarian
            {
                ReaderDetails = new Reader()
            };

            // Assert
            librarian.ReaderDetails.Should().NotBeNull();
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var librarian = new Librarian();

            // Assert
            librarian.Should().NotBeNull();
        }

        [TestMethod]
        public void Equality_ShouldBeBasedOnId()
        {
            // Arrange
            var id = Guid.NewGuid();
            var librarian1 = new Librarian { Id = id };
            var librarian2 = new Librarian { Id = id };

            // Act & Assert
            librarian1.Id.Should().Be(librarian2.Id);
        }
    }
}
