using AutoFixture;
using DomainModel.Entities;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDomainModel.UnitTests.Entities
{
    [ExcludeFromCodeCoverage]
    [TestClass]
    public class ReaderTests : EntityTestBase<Reader>
    {
        [TestMethod]
        public void Constructor_ShouldInitializeCollections()
        {
            // Act
            var reader = new Reader();

            // Assert
            reader.Borrowings.Should().NotBeNull();
            reader.Borrowings.Should().BeEmpty();
        }

        [TestMethod]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange & Act
            var reader1 = new Reader();
            var reader2 = new Reader();

            // Assert
            reader1.Id.Should().NotBeEmpty();
            reader2.Id.Should().NotBeEmpty();
            reader1.Id.Should().NotBe(reader2.Id);
        }

        [TestMethod]
        public void ValidReader_ShouldPassValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .With(r => r.FirstName, "John")
                .With(r => r.LastName, "Doe")
                .With(r => r.Address, "123 Main St, City")
                .With(r => r.DateOfBirth, DateTime.Now.AddYears(-30))
                .With(r => r.PhoneNumber, "+1234567890")
                .With(r => r.Email, "john.doe@example.com")
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().BeEmpty();
        }

        [TestMethod]
        public void FirstName_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .Without(r => r.FirstName)
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("First Name is required"));
        }

        [TestMethod]
        public void FirstName_WhenContainsNumbers_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .With(r => r.FirstName, "John123")
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("First Name can only contain letters and spaces"));
        }

        [TestMethod]
        public void LastName_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .Without(r => r.LastName)
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Last Name is required"));
        }

        [TestMethod]
        public void Address_WhenNullOrEmpty_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .Without(r => r.Address)
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Address is required"));
        }

        [TestMethod]
        public void Address_WhenTooShort_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .With(r => r.Address, "123")
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Address must be between 5 and 300 characters"));
        }

        [TestMethod]
        public void PhoneNumber_WhenInvalidFormat_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .With(r => r.PhoneNumber, "invalid-phone")
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Invalid phone number format"));
        }

        [TestMethod]
        public void PhoneNumber_WhenTooShort_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .With(r => r.PhoneNumber, "123")
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Phone number must be between 10 and 20 characters"));
        }

        [TestMethod]
        public void Email_WhenInvalidFormat_ShouldFailValidation()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .With(r => r.Email, "invalid-email")
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            validationResults.Should().Contain(vr =>
                vr.ErrorMessage.Contains("Invalid email address format"));
        }

        [TestMethod]
        public void AgeValidation_WhenUnder14_ShouldBeCaughtByValidator()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .With(r => r.DateOfBirth, DateTime.Now.AddYears(-13))
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            reader.DateOfBirth.Should().BeAfter(DateTime.Now.AddYears(-14));
        }

        [TestMethod]
        public void ContactMethodValidation_WhenNoPhoneOrEmail_ShouldBeCaughtByValidator()
        {
            // Arrange
            var reader = _fixture.Build<Reader>()
                .Without(r => r.PhoneNumber)
                .Without(r => r.Email)
                .Create();

            // Act
            var validationResults = ValidateEntity(reader);

            // Assert
            reader.PhoneNumber.Should().BeNull();
            reader.Email.Should().BeNull();
        }

        [TestMethod]
        public void Borrowings_ShouldAllowAdding()
        {
            // Arrange
            var reader = new Reader();
            var borrowing = new Borrowing();

            // Act
            reader.Borrowings.Add(borrowing);

            // Assert
            reader.Borrowings.Should().Contain(borrowing);
        }

        [TestMethod]
        public void LibrarianAccount_SetterShouldBeProtected()
        {
            // Arrange
            var property = typeof(Reader).GetProperty(nameof(Reader.LibrarianAccount));
            var setMethod = property?.GetSetMethod(nonPublic: true);

            // Assert
            setMethod.Should().NotBeNull();
            setMethod.IsFamily.Should().BeTrue();
        }

        [TestMethod]
        public void LibrarianAccount_ProtectedSetter_ShouldBeAssignableViaReflection()
        {
            // Arrange
            var reader = new Reader();
            var librarian = new Librarian();

            var property = typeof(Reader).GetProperty(nameof(Reader.LibrarianAccount));
            var setMethod = property.GetSetMethod(nonPublic: true);

            // Act
            setMethod.Invoke(reader, new object[] { librarian });

            // Assert
            reader.LibrarianAccount.Should().Be(librarian);
        }

        [TestMethod]
        public void PropertySetters_ShouldBePublicForMappings()
        {
            // Arrange & Act
            var reader = new Reader
            {
                FirstName = "Test",
                LastName = "User",
                Address = "Test Address",
                DateOfBirth = new DateTime(1990, 1, 1)
            };

            // Assert
            reader.FirstName.Should().Be("Test");
            reader.LastName.Should().Be("User");
            reader.Address.Should().Be("Test Address");
            reader.DateOfBirth.Should().Be(new DateTime(1990, 1, 1));
        }
    }
}
